Repository cse110-sp25-group-10/Flashcard-Project, pull requests merged in 2025-06, with the labels that each got.

#70 Add documentation generation
  .github/workflows/deploy-docs.yml
  .github/workflows/deploy-site.yml
  docs/add.js.html
  docs/fonts/OpenSans-Bold-webfont.eot
  docs/fonts/OpenSans-Bold-webfont.svg
  docs/fonts/OpenSans-Bold-webfont.woff
  docs/fonts/OpenSans-BoldItalic-webfont.eot
  docs/fonts/OpenSans-BoldItalic-webfont.svg
  docs/fonts/OpenSans-BoldItalic-webfont.woff
  docs/fonts/OpenSans-Italic-webfont.eot
  docs/fonts/OpenSans-Italic-webfont.svg
  docs/fonts/OpenSans-Italic-webfont.woff
  docs/fonts/OpenSans-Light-webfont.eot
  docs/fonts/OpenSans-Light-webfont.svg
  docs/fonts/OpenSans-Light-webfont.woff
  docs/fonts/OpenSans-LightItalic-webfont.eot
  docs/fonts/OpenSans-LightItalic-webfont.svg
  docs/fonts/OpenSans-LightItalic-webfont.woff
  docs/fonts/OpenSans-Regular-webfont.eot
  docs/fonts/OpenSans-Regular-webfont.svg
  docs/fonts/OpenSans-Regular-webfont.woff
  docs/global.html
  docs/index.html
  docs/scripts/linenumber.js
  docs/scripts/prettify/Apache-License-2.0.txt
  docs/scripts/prettify/lang-css.js
  docs/scripts/prettify/prettify.js
  docs/styles/jsdoc-default.css
  docs/styles/prettify-jsdoc.css
  docs/styles/prettify-tomorrow.css
Labels: size::s, devops

#63 Crud functionality
  assets/icons/favicon.ico
  index.html
  package-lock.json
  scripts/components/CardPreview.js
  scripts/components/DeckPreview.js
  scripts/index.js
  scripts/screens/CreateScreen.js
  scripts/screens/DeckScreen.js
  scripts/screens/ExistingScreen.js
  scripts/screens/HomeScreen.js
  src/mockup_pages/prepare_speech.html
Labels: feature, help wanted, size::l

#80 Improve CSS for the prepare speech screen
  scripts/components/CardPreview.js
  scripts/screens/CreateScreen.js
  stylesheets/preparing_speech.css
  stylesheets/styles.css
Labels: size::m

#90 Removed time as an extra, unnecessary parameter of Card()
  __tests__/crud.test.js
  scripts/components/CardPreview.js
  scripts/database.js
  scripts/deck.js
  scripts/index.js
  scripts/screens/CreateScreen.js
  scripts/screens/StudyScreen.js
  stylesheets/preparing_speech.css
  stylesheets/study_screen.css
  stylesheets/styles.css
Labels: size::s

#96 E2E testing without merge conflicts
  __tests__/CreateDeck.e2e.test.js
  __tests__/DeleteDeck.e2e.test.js
  __tests__/EditDeck.e2e.test.js
  __tests__/FullDeckFlow.e2e.test.js
  jest-puppeteer.config.js
  package-lock.json
  package.json
Labels: size::l, tests

#100 renamed from Flashcard-Project to 10x-Speech
  .github/workflows/ci.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/deploy-site.yml
  package-lock.json
Labels: size::s
