Repository cse110-sp25-group-10/Flashcard-Project, pull requests merged in 2025-05, with the labels that each got.

#2 removed bad variable name
  scripts/script.js
Labels: size::s

#12 Alex/readme update
  README.md
  package.json
Labels: size::s

#33 Add validation to create card function + sample tests
  __tests__/crud.test.js
  scripts/deck.js
Labels: feature, size::s

#39 Taha/delete card
  scripts/deck.js
Labels: size::s

#38 added validation for reading card
  scripts/deck.js
Labels: size::s

#42 getting rid of buggy human review
  .github/workflows/human_review.yml
  package-lock.json
Labels: devops

#41 Added more rules to match guidelines
  eslint.config.mjs
  package.json
  scripts/script.js
Labels: size::s

#25 UI Templates
  .vscode/settings.json
  index.html
  src/card.html
  src/mockup_pages/deck_selection.html
  src/mockup_pages/empty_deck_selection.html
  src/mockup_pages/existing_flashcard.html
  src/mockup_pages/home.html
  src/mockup_pages/prepare_speech.html
  src/placeholder_card_image.png
  src/styles/card_style.css
Labels: size::m

#45 Render
  index.html
  scripts/card_creation/CardCreation.js
  scripts/deck.js
  scripts/index.js
  scripts/screens/CreateScreen.js
  scripts/screens/HomeScreen.js
Labels: feature, size::s

#49 Implement some basic functionality in the deck creation screen
  index.html
  scripts/card_creation/CardCreation.js
  scripts/card_creation/CardCreationCSS.js
  scripts/card_creation/CardCreationHTML.js
  scripts/components/CardPreview.js
  scripts/deck.js
  scripts/index.js
  scripts/screens/CreateScreen.js
  src/styles/card_style.css
  stylesheets/styles.css
Labels: feature, size::m
